[versions]
kotlin = "2.2.0"
shadow = "7.1.2"
resourcefactory = "1.3.0"
runpaper = "2.1.0"
paperweight = "2.0.0-beta.17"
paper = "1.21.6-R0.1-SNAPSHOT"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
resourcefactory = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version.ref = "resourcefactory" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runpaper" }
