[versions]
kotlin = "1.8.22"
shadow = "7.1.2"
pluginyml = "0.6.0"
runpaper = "2.1.0"
paperweight = "1.5.5"
paper = "1.20.1-R0.1-SNAPSHOT"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
pluginyml = { id = "net.minecrell.plugin-yml.paper", version.ref = "pluginyml" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runpaper" }
